export const COLORS = {
  NAVY: "#002854",
  GOLD: "#FFC600",
  DARK: "#231F20",
  SURFACE: "#F8F7F4",
  BORDER: "#D9D9D9",
  WHITE: "#FFFFFF",
  LIGHT_BLUE: "#A7DCFB",
  STEEL: "#98AFC9",
  BRIGHT_BLUE: "#00A0FB",
  BLUE_GRAY: "#436080",
} as const;

export const PILLARS = [
  {
    id: "dwa",
    title: "DWA",
    subtitle: "Document & Workflow Automation",
    href: "/dwa",
    active: true,
    gradient: "from-[#002854] via-[#1E4D8C] to-[#00A0FB]",
    image: "/pillar-dwa.jpg",
    icon: "/icon-dwa.svg",
  },
  {
    id: "ap-ar",
    title: "AP & AR",
    subtitle: "Accounts Payable & Accounts Receivable Automation",
    href: "/ap-ar",
    active: false,
    gradient: "from-[#231F20] via-[#002854] to-[#436080]",
    image: "/pillar-apar.jpg",
    icon: "/icon-apar.svg",
  },
  {
    id: "print",
    title: "Print",
    subtitle: "Print Management & Output",
    href: "/print",
    active: false,
    gradient: "from-[#436080] via-[#002854] to-[#231F20]",
    image: "/pillar-print.jpg",
    icon: "/icon-print.svg",
  },
  {
    id: "pdf",
    title: "PDF",
    subtitle: "PDF Productivity",
    href: "/pdf",
    active: false,
    gradient: "from-[#002854] via-[#98AFC9] to-[#A7DCFB]",
    image: "/pillar-pdf.jpg",
    icon: "/icon-pdf.svg",
  },
] as const;
